### ISSUE TITLE
pip broken

### ISSUE THREAD

**Issue by Martincccc** [WFP-VAM/vam.whittaker#2]
Hi WFP-VAM

It seems that the `pip` repository is broken. I got this issue : `gcc: error: src/_whittaker.c: No such file or directory`

Using the `git clone ... pip install .` works good.

Thanks

Martin

**Comment by valpesendorfer** [comment]
Thanks for your report @Martincccc!

This is due to missing both `cython` and the  compiled `_whittaker.c` extension (which is not distributed at the moment). As an easy fix, you can also install `cython` prior to running `pip install vam.whittaker`. 

We'll look into distributing the extension so this won't happen again.
